- include: apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: setup postgres db
  become_user: postgres
  postgresql_db: name={{ item }}
  with_items: "{{ db_names }}"

- name: setup postgres users
  become_user: postgres
  postgresql_user: "name={{ db_user }} role_attr_flags=NOSUPERUSER,CREATEDB,LOGIN password={{ db_password }}"

- name: setup user permissions
  become_user: postgres
  postgresql_user: "db={{ item }} name={{ db_user }} priv=ALL"
  with_items: "{{ db_names }}"

- name: allow password authentication
  when: ansible_distribution == 'Ubuntu'
  template: src=templates/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
  become_user: postgres
  notify:
    - restart postgres
